// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateMetricRequest struct {
	// Metric to add to task
	Request shared.Metric `request:"mediaType=application/json"`
}

type CreateMetricResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	Metric      *shared.Metric
	StatusCode  int
	RawResponse *http.Response
}
