// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type CreateDatasetRequest struct {
	// New Dataset to create
	Request shared.Dataset `request:"mediaType=application/json"`
}

type CreateDatasetResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	CreateDatasetResponse *shared.CreateDatasetResponse
	StatusCode            int
	RawResponse           *http.Response
}
