// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type DeletePromptRequest struct {
	// The id of the prompt
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

type DeletePromptResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	PromptDeleteResponse *shared.PromptDeleteResponse
	StatusCode           int
	RawResponse          *http.Response
}
