// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type FindAllTasksRequest struct {
	// Fetch a particular task by name
	Request *string `request:"mediaType=application/json"`
}

type FindAllTasksResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	StatusCode            int
	RawResponse           *http.Response
	// Successful response
	Tasks *shared.Tasks
}
