// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type FindPromptsRequest struct {
	// Find prompts by task or name
	Request *shared.FindPromptsInput `request:"mediaType=application/json"`
}

type FindPromptsResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	Prompts     *shared.Prompts
	StatusCode  int
	RawResponse *http.Response
}
