// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type FindFineTunedModelsRequest struct {
	// Find fine-tuned models by task or name
	Request *shared.FineTunedModelsInput `request:"mediaType=application/json"`
}

type FindFineTunedModelsResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	FineTunedModelsResponse *shared.FineTunedModelsResponse
	StatusCode              int
	RawResponse             *http.Response
}
