// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type FindDatasetsRequest struct {
	// Find datasets by task name.
	Request *shared.FindDatasetsInput `request:"mediaType=application/json"`
}

type FindDatasetsResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	FindDatasetsResponse *shared.FindDatasetsResponse
	StatusCode           int
	RawResponse          *http.Response
}
