// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type GetGenerationRequest struct {
	// Get Generations
	Request shared.GenerationInput `request:"mediaType=application/json"`
}

type GetGenerationResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	GenerationOutputs *shared.GenerationOutputs
	StatusCode        int
	RawResponse       *http.Response
}
