// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type IngestGenerationsRequest struct {
	// Ingest generations
	Request shared.Generations `request:"mediaType=application/json"`
}

type IngestGenerationsResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	Generations *shared.Generations
	StatusCode  int
	RawResponse *http.Response
}
