// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type ModelPromptCreateGenerationRequest struct {
	// Prompt to add to task
	Request shared.ModelPromptGenerationInput `request:"mediaType=application/json"`
}

type ModelPromptCreateGenerationResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	// Successful response
	ModelPromptGenerationOutput *shared.ModelPromptGenerationOutput
	StatusCode                  int
	RawResponse                 *http.Response
}
