// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/honeyhive-go-sdk/pkg/models/shared"
	"net/http"
)

type TaskCreateGenerationRequest struct {
	// Create tasks
	Request shared.TaskGenerationInput `request:"mediaType=application/json"`
}

type TaskCreateGenerationResponse struct {
	// Bad Request error
	APIResponseBadRequest *shared.APIResponseBadRequest
	ContentType           string
	StatusCode            int
	RawResponse           *http.Response
	// Successful response
	TaskGenerationOutput *shared.TaskGenerationOutput
}
