// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// APIResponseBadRequest - Bad Request error
type APIResponseBadRequest struct {
	Error  *string `json:"error,omitempty"`
	Status *int    `json:"status,omitempty"`
}
