// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// DeleteDatasetResponse - Successful response
type DeleteDatasetResponse struct {
	// true if dataset was deleted
	Deleted *bool `json:"deleted,omitempty"`
}
