// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FeedbackFeedbackJSON struct {
	Comment *string `json:"comment,omitempty"`
	Score   *int64  `json:"score,omitempty"`
}

// Feedback - Create feedback
type Feedback struct {
	FeedbackJSON *FeedbackFeedbackJSON `json:"feedback_json,omitempty"`
	GenerationID *string               `json:"generation_id,omitempty"`
	Task         *string               `json:"task,omitempty"`
	Timestamp    *string               `json:"timestamp,omitempty"`
}
