// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FindMetricsInput - Find metrics by task name.
type FindMetricsInput struct {
	TaskName *string `json:"task_name,omitempty"`
}
