// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FindPromptsInput - Find prompts by task or name
type FindPromptsInput struct {
	Name *string `json:"name,omitempty"`
	Task *string `json:"task,omitempty"`
}
