// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// FineTunedModelsInput - Find fine-tuned models by task or name
type FineTunedModelsInput struct {
	ModelID *string `json:"model_id,omitempty"`
	Task    *string `json:"task,omitempty"`
}
