// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GenerationOutputs - Successful response
type GenerationOutputs struct {
	Prompts []GenerationOutput `json:"prompts,omitempty"`
}
