// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Generations - Ingest generations
type Generations struct {
	Generations []Generation `json:"generations,omitempty"`
}
