// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// GenerationInput - Get Generations
type GenerationInput struct {
	Limit   *int64  `json:"limit,omitempty"`
	Model   *string `json:"model,omitempty"`
	Task    *string `json:"task,omitempty"`
	Version *string `json:"version,omitempty"`
}
