// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type MetricsResponse struct {
	CreatedAt *string `json:"created_at,omitempty"`
	// id of the metric
	ID *string `json:"id,omitempty"`
	// name of the metric
	MetricName *string `json:"metric_name,omitempty"`
	// value of the metric
	MetricValue *string `json:"metric_value,omitempty"`
	TaskName    *string `json:"task_name,omitempty"`
	UpdatedAt   *string `json:"updated_at,omitempty"`
}
