// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Metric - Metric to add to task
type Metric struct {
	CodeSnippet *string `json:"code_snippet,omitempty"`
	Name        *string `json:"name,omitempty"`
	TaskName    *string `json:"task_name,omitempty"`
}
