// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// PromptDeleteResponse - Successful response
type PromptDeleteResponse struct {
	// true if prompt was deleted
	Deleted *bool `json:"deleted,omitempty"`
}
